// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package note

import (
	"database/sql"
	"time"
)

type Note struct {
	ID          int64        `json:"id"`
	Content     string       `json:"content"`
	CreatedAt   time.Time    `json:"created_at"`
	CompletedAt sql.NullTime `json:"completed_at"`
	IsTask      bool         `json:"is_task"`
}

type NoteTag struct {
	NoteID int64 `json:"note_id"`
	TagID  int64 `json:"tag_id"`
}

type NotesFt struct {
	Content string `json:"content"`
}

type Tag struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}
