// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package note

import (
	"time"
)

type Note struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type NoteTag struct {
	NoteID int64 `json:"note_id"`
	TagID  int64 `json:"tag_id"`
}

type NotesFt struct {
	Name    string `json:"name"`
	Content string `json:"content"`
}

type Tag struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}
