// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package note

import (
	"context"
)

type Querier interface {
	// Note Tags Relationships
	AddTagToNote(ctx context.Context, arg AddTagToNoteParams) error
	// Notes
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	// Tags
	CreateTag(ctx context.Context, name string) (Tag, error)
	DeleteNoteByID(ctx context.Context, id int64) (int64, error)
	DeleteTaskByID(ctx context.Context, id int64) (int64, error)
	GetNoteByID(ctx context.Context, id int64) (Note, error)
	GetTag(ctx context.Context, name string) (Tag, error)
	ListNotes(ctx context.Context) ([]Note, error)
	ListTags(ctx context.Context, name string) ([]Tag, error)
	ListTagsByNoteID(ctx context.Context, noteID int64) ([]string, error)
	ListTasks(ctx context.Context) ([]Note, error)
	MarkNoteCompleted(ctx context.Context, id int64) (int64, error)
	SearchNotes(ctx context.Context, arg SearchNotesParams) ([]Note, error)
	SearchNotesByContent(ctx context.Context, arg SearchNotesByContentParams) ([]Note, error)
	SearchNotesByTag(ctx context.Context, arg SearchNotesByTagParams) ([]Note, error)
	SearchNotesByTagAndContent(ctx context.Context, arg SearchNotesByTagAndContentParams) ([]Note, error)
	UpdateNoteContentByID(ctx context.Context, arg UpdateNoteContentByIDParams) (Note, error)
}

var _ Querier = (*Queries)(nil)
