// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package note

import (
	"context"
)

const addTagToNote = `-- name: AddTagToNote :exec
INSERT INTO
    note_tags (note_id, tag_id)
VALUES
    (?, ?)
`

type AddTagToNoteParams struct {
	NoteID int64 `json:"note_id"`
	TagID  int64 `json:"tag_id"`
}

// Note Tags Relationships
func (q *Queries) AddTagToNote(ctx context.Context, arg AddTagToNoteParams) error {
	_, err := q.db.ExecContext(ctx, addTagToNote, arg.NoteID, arg.TagID)
	return err
}

const createNote = `-- name: CreateNote :one
INSERT INTO
	note (content, is_task)
VALUES
	(?, ?) RETURNING id, content, created_at, completed_at, is_task
`

// Notes
func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote, arg.Content, arg.IsTask)
	var i Note
	err := row.Scan(&i.ID, &i.Content, &i.CreatedAt, &i.CompletedAt, &i.IsTask)
	return i, err
}

type CreateNoteParams struct {
	Content string `json:"content"`
	IsTask  bool   `json:"is_task"`
}

const createTag = `-- name: CreateTag :one
INSERT INTO
    tags (name)
VALUES
    (?) RETURNING id, name, created_at
`

// Tags
func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getNotesByTagWithLimit = `-- name: GetNotesByTagWithLimit :many
SELECT
	n.id, n.content, n.created_at, n.completed_at, n.is_task
FROM
    note n
    INNER JOIN note_tags nt ON n.id = nt.note_id
    INNER JOIN tags t ON nt.tag_id = t.id
WHERE
    t.name = ?
ORDER BY
    n.created_at DESC
LIMIT
    ?
`

type GetNotesByTagWithLimitParams struct {
	Name  string `json:"name"`
	Limit int64  `json:"limit"`
}

func (q *Queries) GetNotesByTagWithLimit(ctx context.Context, arg GetNotesByTagWithLimitParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotesByTagWithLimit, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(&i.ID, &i.Content, &i.CreatedAt, &i.CompletedAt, &i.IsTask); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTag = `-- name: GetTag :one
SELECT
    id, name, created_at
FROM
    tags
WHERE
    name = ?
`

func (q *Queries) GetTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT
	id, content, created_at, completed_at, is_task
FROM
    note
ORDER BY
    created_at DESC
`

func (q *Queries) ListNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(&i.ID, &i.Content, &i.CreatedAt, &i.CompletedAt, &i.IsTask); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT
    id, name, created_at
FROM
    tags
WHERE
    name LIKE ?
`

func (q *Queries) ListTags(ctx context.Context, name string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByNoteID = `-- name: ListTagsByNoteID :many
SELECT
    t.name
FROM
    tags t
    INNER JOIN note_tags nt ON t.id = nt.tag_id
WHERE
    nt.note_id = ?
ORDER BY
    t.name
`

func (q *Queries) ListTagsByNoteID(ctx context.Context, noteID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByNoteID, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNotesSimple = `-- name: SearchNotesSimple :many
SELECT
	id, content, created_at, completed_at, is_task
FROM
    note
WHERE
    content LIKE ?
ORDER BY
    created_at DESC
`

// Simple text search for now (FTS5 will be implemented manually)
func (q *Queries) SearchNotesSimple(ctx context.Context, content string) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, searchNotesSimple, content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(&i.ID, &i.Content, &i.CreatedAt, &i.CompletedAt, &i.IsTask); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNoteCompleted = `-- name: MarkNoteCompleted :execrows
UPDATE
    note
SET
    completed_at = CURRENT_TIMESTAMP
WHERE
    id = ?
    AND completed_at IS NULL
`

func (q *Queries) MarkNoteCompleted(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNoteCompleted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTaskByID = `-- name: DeleteTaskByID :execrows
DELETE FROM
    note
WHERE
    id = ?
    AND is_task = 1
`

func (q *Queries) DeleteTaskByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTaskByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteNoteByID = `-- name: DeleteNoteByID :execrows
DELETE FROM
    note
WHERE
    id = ?
`

func (q *Queries) DeleteNoteByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNoteByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
