// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package note

import (
	"context"
	"database/sql"
	"strings"
)

const addTagToNote = `-- name: AddTagToNote :exec
INSERT INTO
  note_tags (note_id, tag_id)
VALUES
  (?, ?)
`

type AddTagToNoteParams struct {
	NoteID int64 `json:"note_id"`
	TagID  int64 `json:"tag_id"`
}

// Note Tags Relationships
func (q *Queries) AddTagToNote(ctx context.Context, arg AddTagToNoteParams) error {
	_, err := q.db.ExecContext(ctx, addTagToNote, arg.NoteID, arg.TagID)
	return err
}

const addTagToTaskSeries = `-- name: AddTagToTaskSeries :exec
INSERT INTO
  task_series_tags (task_series_id, tag_id)
VALUES
  (?, ?)
`

type AddTagToTaskSeriesParams struct {
	TaskSeriesID int64 `json:"task_series_id"`
	TagID        int64 `json:"tag_id"`
}

func (q *Queries) AddTagToTaskSeries(ctx context.Context, arg AddTagToTaskSeriesParams) error {
	_, err := q.db.ExecContext(ctx, addTagToTaskSeries, arg.TaskSeriesID, arg.TagID)
	return err
}

const createNote = `-- name: CreateNote :one
INSERT INTO
  note (
    content,
    is_task,
    due_at,
    task_series_id,
    recurrence_rule,
    recurrence_weekday,
    recurrence_day_of_month
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?) RETURNING id,
  content,
  created_at,
  completed_at,
  is_task,
  due_at,
  task_series_id,
  recurrence_rule,
  recurrence_weekday,
  recurrence_day_of_month
`

type CreateNoteParams struct {
	Content              string         `json:"content"`
	IsTask               int64          `json:"is_task"`
	DueAt                sql.NullTime   `json:"due_at"`
	TaskSeriesID         sql.NullInt64  `json:"task_series_id"`
	RecurrenceRule       sql.NullString `json:"recurrence_rule"`
	RecurrenceWeekday    sql.NullInt64  `json:"recurrence_weekday"`
	RecurrenceDayOfMonth sql.NullInt64  `json:"recurrence_day_of_month"`
}

// Notes
func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.Content,
		arg.IsTask,
		arg.DueAt,
		arg.TaskSeriesID,
		arg.RecurrenceRule,
		arg.RecurrenceWeekday,
		arg.RecurrenceDayOfMonth,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.IsTask,
		&i.DueAt,
		&i.TaskSeriesID,
		&i.RecurrenceRule,
		&i.RecurrenceWeekday,
		&i.RecurrenceDayOfMonth,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO
  tags (name)
VALUES
  (?) RETURNING id, name, created_at
`

// Tags
func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createTaskSeries = `-- name: CreateTaskSeries :one
INSERT INTO
  task_series (
    content,
    recurrence_rule,
    recurrence_weekday,
    recurrence_day_of_month
  )
VALUES
  (?, ?, ?, ?) RETURNING id,
  content,
  recurrence_rule,
  recurrence_weekday,
  recurrence_day_of_month,
  active,
  created_at
`

type CreateTaskSeriesParams struct {
	Content              string        `json:"content"`
	RecurrenceRule       string        `json:"recurrence_rule"`
	RecurrenceWeekday    sql.NullInt64 `json:"recurrence_weekday"`
	RecurrenceDayOfMonth sql.NullInt64 `json:"recurrence_day_of_month"`
}

// Task series
func (q *Queries) CreateTaskSeries(ctx context.Context, arg CreateTaskSeriesParams) (TaskSeries, error) {
	row := q.db.QueryRowContext(ctx, createTaskSeries,
		arg.Content,
		arg.RecurrenceRule,
		arg.RecurrenceWeekday,
		arg.RecurrenceDayOfMonth,
	)
	var i TaskSeries
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.RecurrenceRule,
		&i.RecurrenceWeekday,
		&i.RecurrenceDayOfMonth,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllTagsFromNote = `-- name: DeleteAllTagsFromNote :exec
DELETE FROM note_tags
WHERE
  note_id = ?
`

func (q *Queries) DeleteAllTagsFromNote(ctx context.Context, noteID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllTagsFromNote, noteID)
	return err
}

const deleteAllTagsFromTaskSeries = `-- name: DeleteAllTagsFromTaskSeries :exec
DELETE FROM task_series_tags
WHERE
  task_series_id = ?
`

func (q *Queries) DeleteAllTagsFromTaskSeries(ctx context.Context, taskSeriesID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllTagsFromTaskSeries, taskSeriesID)
	return err
}

const deleteNoteByID = `-- name: DeleteNoteByID :execrows
DELETE FROM note
WHERE
  id = ?
`

func (q *Queries) DeleteNoteByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNoteByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePendingNotesByTaskSeriesID = `-- name: DeletePendingNotesByTaskSeriesID :execrows
DELETE FROM note
WHERE
  task_series_id = ?
  AND completed_at IS NULL
`

func (q *Queries) DeletePendingNotesByTaskSeriesID(ctx context.Context, taskSeriesID sql.NullInt64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePendingNotesByTaskSeriesID, taskSeriesID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTaskByID = `-- name: DeleteTaskByID :execrows
DELETE FROM note
WHERE
  id = ?
  AND is_task = 1
`

func (q *Queries) DeleteTaskByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTaskByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT
  id,
  content,
  created_at,
  completed_at,
  is_task,
  due_at,
  task_series_id,
  recurrence_rule,
  recurrence_weekday,
  recurrence_day_of_month
FROM
  note
WHERE
  id = ?
`

func (q *Queries) GetNoteByID(ctx context.Context, id int64) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNoteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.IsTask,
		&i.DueAt,
		&i.TaskSeriesID,
		&i.RecurrenceRule,
		&i.RecurrenceWeekday,
		&i.RecurrenceDayOfMonth,
	)
	return i, err
}

const getPendingNoteByTaskSeriesID = `-- name: GetPendingNoteByTaskSeriesID :one
SELECT
  id,
  content,
  created_at,
  completed_at,
  is_task,
  due_at,
  task_series_id,
  recurrence_rule,
  recurrence_weekday,
  recurrence_day_of_month
FROM
  note
WHERE
  task_series_id = ?
  AND completed_at IS NULL
`

func (q *Queries) GetPendingNoteByTaskSeriesID(ctx context.Context, taskSeriesID sql.NullInt64) (Note, error) {
	row := q.db.QueryRowContext(ctx, getPendingNoteByTaskSeriesID, taskSeriesID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.IsTask,
		&i.DueAt,
		&i.TaskSeriesID,
		&i.RecurrenceRule,
		&i.RecurrenceWeekday,
		&i.RecurrenceDayOfMonth,
	)
	return i, err
}

const getTag = `-- name: GetTag :one
SELECT
  id, name, created_at
FROM
  tags
WHERE
  name = ?
`

func (q *Queries) GetTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTaskSeriesByID = `-- name: GetTaskSeriesByID :one
SELECT
  id,
  content,
  recurrence_rule,
  recurrence_weekday,
  recurrence_day_of_month,
  active,
  created_at
FROM
  task_series
WHERE
  id = ?
`

func (q *Queries) GetTaskSeriesByID(ctx context.Context, id int64) (TaskSeries, error) {
	row := q.db.QueryRowContext(ctx, getTaskSeriesByID, id)
	var i TaskSeries
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.RecurrenceRule,
		&i.RecurrenceWeekday,
		&i.RecurrenceDayOfMonth,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskSeriesByNoteID = `-- name: GetTaskSeriesByNoteID :one
SELECT
  ts.id,
  ts.content,
  ts.recurrence_rule,
  ts.recurrence_weekday,
  ts.recurrence_day_of_month,
  ts.active,
  ts.created_at
FROM
  task_series ts
  INNER JOIN note n ON n.task_series_id = ts.id
WHERE
  n.id = ?
`

func (q *Queries) GetTaskSeriesByNoteID(ctx context.Context, id int64) (TaskSeries, error) {
	row := q.db.QueryRowContext(ctx, getTaskSeriesByNoteID, id)
	var i TaskSeries
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.RecurrenceRule,
		&i.RecurrenceWeekday,
		&i.RecurrenceDayOfMonth,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT
  id,
  content,
  created_at,
  completed_at,
  is_task,
  due_at,
  task_series_id,
  recurrence_rule,
  recurrence_weekday,
  recurrence_day_of_month
FROM
  note
ORDER BY
  created_at DESC
`

func (q *Queries) ListNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.IsTask,
			&i.DueAt,
			&i.TaskSeriesID,
			&i.RecurrenceRule,
			&i.RecurrenceWeekday,
			&i.RecurrenceDayOfMonth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT
  id, name, created_at
FROM
  tags
WHERE
  name LIKE ?
`

func (q *Queries) ListTags(ctx context.Context, name string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByNoteID = `-- name: ListTagsByNoteID :many
SELECT
  t.name
FROM
  tags t
  INNER JOIN note_tags nt ON t.id = nt.tag_id
WHERE
  nt.note_id = ?
ORDER BY
  t.name
`

func (q *Queries) ListTagsByNoteID(ctx context.Context, noteID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByNoteID, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByNoteIDs = `-- name: ListTagsByNoteIDs :many
SELECT
  nt.note_id,
  t.name
FROM
  note_tags nt
  INNER JOIN tags t ON t.id = nt.tag_id
WHERE
  nt.note_id IN (/*SLICE:note_ids*/?)
ORDER BY
  nt.note_id,
  t.name
`

type ListTagsByNoteIDsRow struct {
	NoteID int64  `json:"note_id"`
	Name   string `json:"name"`
}

func (q *Queries) ListTagsByNoteIDs(ctx context.Context, noteIds []int64) ([]ListTagsByNoteIDsRow, error) {
	query := listTagsByNoteIDs
	var queryParams []interface{}
	if len(noteIds) > 0 {
		for _, v := range noteIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:note_ids*/?", strings.Repeat(",?", len(noteIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:note_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsByNoteIDsRow
	for rows.Next() {
		var i ListTagsByNoteIDsRow
		if err := rows.Scan(&i.NoteID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByTaskSeriesID = `-- name: ListTagsByTaskSeriesID :many
SELECT
  t.name
FROM
  tags t
  INNER JOIN task_series_tags tst ON t.id = tst.tag_id
WHERE
  tst.task_series_id = ?
ORDER BY
  t.name
`

func (q *Queries) ListTagsByTaskSeriesID(ctx context.Context, taskSeriesID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByTaskSeriesID, taskSeriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT
  id,
  content,
  created_at,
  completed_at,
  is_task,
  due_at,
  task_series_id,
  recurrence_rule,
  recurrence_weekday,
  recurrence_day_of_month
FROM
  note
WHERE
  is_task = 1
ORDER BY
  created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.IsTask,
			&i.DueAt,
			&i.TaskSeriesID,
			&i.RecurrenceRule,
			&i.RecurrenceWeekday,
			&i.RecurrenceDayOfMonth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNoteCompleted = `-- name: MarkNoteCompleted :execrows
UPDATE note
SET
  completed_at = CURRENT_TIMESTAMP
WHERE
  id = ?
  AND completed_at IS NULL
  AND is_task = 1
`

func (q *Queries) MarkNoteCompleted(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNoteCompleted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const searchNotes = `-- name: SearchNotes :many
SELECT
  id,
  content,
  created_at,
  completed_at,
  is_task,
  due_at,
  task_series_id,
  recurrence_rule,
  recurrence_weekday,
  recurrence_day_of_month
FROM
  note
WHERE
  (
    ? = 0
    OR is_task = 1
  )
  AND (
    ? = 0
    OR completed_at IS NOT NULL
  )
  AND (
    ? = 0
    OR completed_at IS NULL
  )
ORDER BY
  created_at DESC
LIMIT
  ?
`

type SearchNotesParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Limit   int64       `json:"limit"`
}

func (q *Queries) SearchNotes(ctx context.Context, arg SearchNotesParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, searchNotes,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.IsTask,
			&i.DueAt,
			&i.TaskSeriesID,
			&i.RecurrenceRule,
			&i.RecurrenceWeekday,
			&i.RecurrenceDayOfMonth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNotesByContent = `-- name: SearchNotesByContent :many
SELECT
  n.id,
  n.content,
  n.created_at,
  n.completed_at,
  n.is_task,
  n.due_at,
  n.task_series_id,
  n.recurrence_rule,
  n.recurrence_weekday,
  n.recurrence_day_of_month
FROM
  notes_fts
  INNER JOIN note n ON n.id = notes_fts.rowid
WHERE
  notes_fts.content MATCH ?
  AND (
    ? = 0
    OR n.is_task = 1
  )
  AND (
    ? = 0
    OR n.completed_at IS NOT NULL
  )
  AND (
    ? = 0
    OR n.completed_at IS NULL
  )
ORDER BY
  n.created_at DESC
LIMIT
  ?
`

type SearchNotesByContentParams struct {
	Content string      `json:"content"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Limit   int64       `json:"limit"`
}

func (q *Queries) SearchNotesByContent(ctx context.Context, arg SearchNotesByContentParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, searchNotesByContent,
		arg.Content,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.IsTask,
			&i.DueAt,
			&i.TaskSeriesID,
			&i.RecurrenceRule,
			&i.RecurrenceWeekday,
			&i.RecurrenceDayOfMonth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNotesByTag = `-- name: SearchNotesByTag :many
SELECT
  n.id,
  n.content,
  n.created_at,
  n.completed_at,
  n.is_task,
  n.due_at,
  n.task_series_id,
  n.recurrence_rule,
  n.recurrence_weekday,
  n.recurrence_day_of_month
FROM
  note n
  INNER JOIN note_tags nt ON n.id = nt.note_id
  INNER JOIN tags t ON nt.tag_id = t.id
WHERE
  t.name = ?
  AND (
    ? = 0
    OR n.is_task = 1
  )
  AND (
    ? = 0
    OR n.completed_at IS NOT NULL
  )
  AND (
    ? = 0
    OR n.completed_at IS NULL
  )
ORDER BY
  n.created_at DESC
LIMIT
  ?
`

type SearchNotesByTagParams struct {
	Name    string      `json:"name"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Limit   int64       `json:"limit"`
}

func (q *Queries) SearchNotesByTag(ctx context.Context, arg SearchNotesByTagParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, searchNotesByTag,
		arg.Name,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.IsTask,
			&i.DueAt,
			&i.TaskSeriesID,
			&i.RecurrenceRule,
			&i.RecurrenceWeekday,
			&i.RecurrenceDayOfMonth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNotesByTagAndContent = `-- name: SearchNotesByTagAndContent :many
SELECT
  n.id,
  n.content,
  n.created_at,
  n.completed_at,
  n.is_task,
  n.due_at,
  n.task_series_id,
  n.recurrence_rule,
  n.recurrence_weekday,
  n.recurrence_day_of_month
FROM
  notes_fts
  INNER JOIN note n ON n.id = notes_fts.rowid
  INNER JOIN note_tags nt ON n.id = nt.note_id
  INNER JOIN tags t ON nt.tag_id = t.id
WHERE
  notes_fts.content MATCH ?
  AND t.name = ?
  AND (
    ? = 0
    OR n.is_task = 1
  )
  AND (
    ? = 0
    OR n.completed_at IS NOT NULL
  )
  AND (
    ? = 0
    OR n.completed_at IS NULL
  )
ORDER BY
  n.created_at DESC
LIMIT
  ?
`

type SearchNotesByTagAndContentParams struct {
	Content string      `json:"content"`
	Name    string      `json:"name"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 interface{} `json:"column_5"`
	Limit   int64       `json:"limit"`
}

func (q *Queries) SearchNotesByTagAndContent(ctx context.Context, arg SearchNotesByTagAndContentParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, searchNotesByTagAndContent,
		arg.Content,
		arg.Name,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.IsTask,
			&i.DueAt,
			&i.TaskSeriesID,
			&i.RecurrenceRule,
			&i.RecurrenceWeekday,
			&i.RecurrenceDayOfMonth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaskSeriesInactive = `-- name: SetTaskSeriesInactive :execrows
UPDATE task_series
SET
  active = 0
WHERE
  id = ?
`

func (q *Queries) SetTaskSeriesInactive(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTaskSeriesInactive, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateNoteAttributesByID = `-- name: UpdateNoteAttributesByID :one
UPDATE note
SET
  content = ?,
  due_at = ?,
  task_series_id = ?,
  recurrence_rule = ?,
  recurrence_weekday = ?,
  recurrence_day_of_month = ?
WHERE
  id = ? RETURNING id,
  content,
  created_at,
  completed_at,
  is_task,
  due_at,
  task_series_id,
  recurrence_rule,
  recurrence_weekday,
  recurrence_day_of_month
`

type UpdateNoteAttributesByIDParams struct {
	Content              string         `json:"content"`
	DueAt                sql.NullTime   `json:"due_at"`
	TaskSeriesID         sql.NullInt64  `json:"task_series_id"`
	RecurrenceRule       sql.NullString `json:"recurrence_rule"`
	RecurrenceWeekday    sql.NullInt64  `json:"recurrence_weekday"`
	RecurrenceDayOfMonth sql.NullInt64  `json:"recurrence_day_of_month"`
	ID                   int64          `json:"id"`
}

func (q *Queries) UpdateNoteAttributesByID(ctx context.Context, arg UpdateNoteAttributesByIDParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNoteAttributesByID,
		arg.Content,
		arg.DueAt,
		arg.TaskSeriesID,
		arg.RecurrenceRule,
		arg.RecurrenceWeekday,
		arg.RecurrenceDayOfMonth,
		arg.ID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.IsTask,
		&i.DueAt,
		&i.TaskSeriesID,
		&i.RecurrenceRule,
		&i.RecurrenceWeekday,
		&i.RecurrenceDayOfMonth,
	)
	return i, err
}

const updateNoteContentByID = `-- name: UpdateNoteContentByID :one
UPDATE note
SET
  content = ?
WHERE
  id = ? RETURNING id,
  content,
  created_at,
  completed_at,
  is_task,
  due_at,
  task_series_id,
  recurrence_rule,
  recurrence_weekday,
  recurrence_day_of_month
`

type UpdateNoteContentByIDParams struct {
	Content string `json:"content"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateNoteContentByID(ctx context.Context, arg UpdateNoteContentByIDParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNoteContentByID, arg.Content, arg.ID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.IsTask,
		&i.DueAt,
		&i.TaskSeriesID,
		&i.RecurrenceRule,
		&i.RecurrenceWeekday,
		&i.RecurrenceDayOfMonth,
	)
	return i, err
}

const updateTaskSeries = `-- name: UpdateTaskSeries :one
UPDATE task_series
SET
  content = ?,
  recurrence_rule = ?,
  recurrence_weekday = ?,
  recurrence_day_of_month = ?,
  active = ?
WHERE
  id = ? RETURNING id,
  content,
  recurrence_rule,
  recurrence_weekday,
  recurrence_day_of_month,
  active,
  created_at
`

type UpdateTaskSeriesParams struct {
	Content              string        `json:"content"`
	RecurrenceRule       string        `json:"recurrence_rule"`
	RecurrenceWeekday    sql.NullInt64 `json:"recurrence_weekday"`
	RecurrenceDayOfMonth sql.NullInt64 `json:"recurrence_day_of_month"`
	Active               int64         `json:"active"`
	ID                   int64         `json:"id"`
}

func (q *Queries) UpdateTaskSeries(ctx context.Context, arg UpdateTaskSeriesParams) (TaskSeries, error) {
	row := q.db.QueryRowContext(ctx, updateTaskSeries,
		arg.Content,
		arg.RecurrenceRule,
		arg.RecurrenceWeekday,
		arg.RecurrenceDayOfMonth,
		arg.Active,
		arg.ID,
	)
	var i TaskSeries
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.RecurrenceRule,
		&i.RecurrenceWeekday,
		&i.RecurrenceDayOfMonth,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
