package note

import (
	"context"
	"database/sql"
)

// Repository defines the data access behavior
type Repository interface {
	SaveNote(ctx context.Context, n *Note) (*Note, error)
	GetNotesByCat(ctx context.Context, catName string) ([]GetNotesByCategoryRow, error)
}

type sqliteRepo struct {
	queries *Queries // This comes from sqlc's generated code
	db      *sql.DB
}

func NewRepository(db *sql.DB) Repository {
	return &sqliteRepo{
		queries: New(db), // New() is generated by sqlc
		db:      db,
	}
}

func (r *sqliteRepo) SaveNote(ctx context.Context, n *Note) (*Note, error) {
	// Map your domain model to sqlc's CreateNoteParams
	res, err := r.queries.CreateNote(ctx, CreateNoteParams{
		CategoryID: n.CategoryID,
		Name:       n.Name,
		Content:    n.Content,
	})
	if err != nil {
		return nil, err
	}
	return &res, nil
}
